apiVersion: apps/v1
kind: Deployment
metadata:
  name: daniscarpa-frontend
  namespace: frontend
  labels:
    app: daniscarpa-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: daniscarpa-frontend
  template:
    metadata:
      labels:
        app: daniscarpa-frontend
    spec:
      containers:
      - name: daniscarpa-frontend
        image: gcr.io/daniscarpa/frontend:latest
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 10
          timeoutSeconds: 5
        # env:
        # - name: API_URL
        #   valueFrom:
        #     secretKeyRef:
        #       name: api-url
        #       key: url
        