apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: daniscarpa-lb
  namespace: frontend
  annotations:
    kubernetes.io/ingress.allow-http: "true"
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - host: www.daniscarpa.com
    http:
      paths:
      - path: /
        backend:
          serviceName: daniscarpa-frontend
          servicePort: frontend