apiVersion: apps/v1
kind: Deployment
metadata:
  name: daniscarpa-backend
  namespace: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: daniscarpa-backend
  template:
    metadata:
      labels:
        app: daniscarpa-backend
    spec:
      containers:
      - name: daniscarpa-backend
        image: gcr.io/daniscarpa/backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: postgresql://daniscarpa:password@localhost:5432/daniscarpa
---
apiVersion: v1
kind: Service
metadata:
  name: daniscarpa-backend
  namespace: backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: backend
  selector:
    app: daniscarpa-backend