apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: thanos-store
  name: thanos-store
  namespace: thanos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-store
  template:
    metadata:
      labels:
        app: thanos-store
    spec:
      containers:
      - args:
        - store
        - --data-dir=/var/thanos/store
        - --objstore.config=/config/thanos.yaml
        image: quay.io/thanos/thanos:v0.10.1
        livenessProbe:
          failureThreshold: 8
          httpGet:
            path: /-/healthy
            port: 10902
            scheme: HTTP
          periodSeconds: 30
        name: thanos-store
        ports:
        - containerPort: 10901
          name: grpc
        - containerPort: 10902
          name: http
        readinessProbe:
          failureThreshold: 20
          httpGet:
            path: /-/ready
            port: 10902
            scheme: HTTP
          periodSeconds: 5
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /var/thanos/store
          name: data
          readOnly: false
        - name: config
          mountPath: /config/
          readOnly: true
      terminationGracePeriodSeconds: 120
      volumes:
        - name: config
          secret:
            defaultMode: 256
            secretName: thanos-objectstorage
  volumeClaimTemplates:
  - metadata:
      labels:
        app: thanos-store
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi