apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
 labels:
   team: devops
 name: prometheus-k8s-backend
 namespace: backend
rules:
 - apiGroups:
     - ""
   resources:
     - services
     - endpoints
     - pods
   verbs:
     - get
     - list
     - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
 labels:
   team: devops
 name: prometheus-k8s-backend
rules:
 - apiGroups:
     - ""
   resources:
     - nodes/metrics
     - services
     - endpoints
     - pods
   verbs:
     - get
     - list
     - watch
 - nonResourceURLs:
     - /metrics
   verbs:
     - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 labels:
   team: devops
 name: prometheus-k8s-backend
 namespace: backend
roleRef:
 apiGroup: rbac.authorization.k8s.io
 kind: Role
 name: prometheus-k8s-backend
subjects:
 - kind: ServiceAccount
   name: prometheus-k8s
   namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
 labels:
   team: devops
 name: prometheus-k8s-backend
roleRef:
 apiGroup: rbac.authorization.k8s.io
 kind: ClusterRole
 name: prometheus-k8s-backend
subjects:
 - kind: ServiceAccount
   name: prometheus-k8s
   namespace: monitoring