apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: daniscarpa-lb
  annotations:
    kubernetes.io/ingress.allow-http: "true"
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - host: www.daniscarpa.com
    http:
      paths:
      - path: /api
        backend:
          serviceName: daniscarpa-backend
          servicePort: backend
      - path: /
        backend:
          serviceName: daniscarpa-frontend
          servicePort: frontend